# Generated by Django 3.0.8 on 2020-07-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_type', models.CharField(choices=[('P', 'PRESENTATION'), ('F', 'FEATURE'), ('A', 'APPLICATION')], max_length=25, verbose_name='Tipo de erro')),
                ('e_msg', models.TextField(verbose_name='Mensagem de erro')),
                ('application', models.CharField(max_length=50, verbose_name='Aplicação')),
                ('layer', models.CharField(choices=[('B', 'BACKEND'), ('F', 'FEATURE'), ('A', 'APPLICATION'), ('D', 'DESKTOP')], max_length=25, verbose_name='Camada')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Hora')),
            ],
        ),
    ]
